[package]
name = "eon_module_random"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]
test = false
[dependencies]
eon_core = { workspace = true }
rand = "0.9.2"

[build-dependencies]
eon_core = { workspace = true }
